location:
  initial: bedroom
  actions: [go]
  rules:
    entrance -- lawn: 
      if state entrance.objects.door.door is closed:
        message: doorNotOpen
        revert: state
  entities:
    entrance:
      - objects.door
    lawn:
      - people.ada
