location:
  - default: bedroom
  - actions: go
  - rules:
    - entrance -- lawn: 
      - require state entrance.door: open
      - message: door_not_open
  - entities:
    - entrance:
      - objects.door
    - lawn:
      - people.ada
