location:
  start: entrance
  actions: [go, describe]
  rules:
    entrance -- lawn:
      if state door is closed:
        message: doorNotOpen
        state: .last
  entities:
    entrance:
      - objects.door
      - people.ada
