location:
  start: bedroom
  actions: [go]
  rules:
    entrance -- lawn:
      if state door is closed:
        message: doorNotOpen
        revert: location
  entities:
    entrance:
      - objects.door
    lawn:
      - people.ada
