location:
  default: bedroom
  actions: [go]
  rules:
    entrance -- lawn: 
      - if not state: entrance.objects.door:open
      - then message: door_not_open
      - then revert: location
  entities:
    entrance:
      - objects.door
    lawn:
      - people.ada
