location:
  default: bedroom
  actions: [go]
  rules:
    - entrance -- lawn: 
      - if not state entrance.objects.door: open
      - set message: door_not_open
  entities:
    entrance:
      - objects.door
    lawn:
      - people.ada
