location:
  start: bedroom
  actions: [go, describe]
  rules:
    entrance -- lawn:
      if property entrance.objects.door.door is closed:
        message: frontDoorNotOpen
        value: .last
    upstairsHallway -- masterBedroom:
      if property masterBedroom.objects.door.door is closed:
        message: masterBedroomDoorLocked
        value: .last
  entities:
    bedroom:
      - objects.letter
    entrance:
      - objects.door
    lawn:
      - people.ada
    masterBedroom:
      - objects.door
