location:
  start: entrance
  actions: [go, describe]
  rules:
    entrance -- lawn:
      if state entrance.objects.door.door is closed:
        message: doorNotOpen
        state: .last
  entities:
    bedroom:
      - objects.letter
    entrance:
      - objects.door
    lawn:
      - people.ada
