conversation:
  default: hello
  actions: [say]
  disable: [who_are_you_really]
  rules:
    - hello:
      - set state: idle
    - who_are_you:
      - set disable: [who_are_you]
      - set enable: [who_are_you_really]
      - set state: idle
    - who_are_you_really:
      - set state: idle
    - where_am_i:
      - set state: idle
