conversation:
  - default: hello
  - actions: say
  - variables:
    - show_who_are_you_really: no
  - rules:
    - hello:
      - set conversation: idle
    - who_are_you:
      - set show_who_are_you_really: yes
    - who_are_you_really:
      - set conversation: idle
    - who_are_you_really:
      - enabled: show_who_are_you_really
    - where_am_i:
      - set conversation: idle
