conversation:
  - default: hello
  - actions: say
  - disable:
    - who_are_you_really
  - rules:
    - hello:
      - state: idle
    - who_are_you:
      - disable: who_are_you
      - enable: who_are_you_really
      - state: idle
    - who_are_you_really:
      - state: idle
    - where_am_i:
      - state: idle
