conversation:
  default: hello
  actions: [say]
  disable: [whoAreYouReally]
  rules:
    hello:
      - state: idle
    whoAreYou:
      - disable: [whoAreYou]
      - enable: [whoAreYouReally]
      - state: idle
    whoAreYouReally:
      - state: idle
    whereAmI:
      - state: idle
