appearance:
  actions: [describe]
  start: floating

conversation:
  start: hello
  actions: [say]
  disable: [whoAreYouReally]
  rules:
    hello:
      state: nothing
    whoAreYou:
      disable: [whoAreYou]
      enable: [whoAreYouReally]
      state: nothing
    whoAreYouReally:
      state: nothing
    whereAmI:
      state: nothing
