door:
  - default: closed
  - actions: [open, close]
  - rules:
      - open -> closed: 
        - require action: closed
        - message: door_already_open
      - closed -> open:
        - require action: open
        - message: door_already_closed
