door:
  initial: closed
  actions: [open, close]
  rules:
    open -> closed: 
      - if action: close
      - then message: doorAlreadyOpen
      - then state: open
    closed -> open:
      - if action: open
      - then message: doorAlreadyClosed
      - then state: closed
