door:
  default: closed
  actions: [open, close]
  rules:
    - open -> closed: 
      - if action: close
      - message: door_already_open
    - closed -> open:
      - if action: open
      - message: door_already_closed
