door:
  start: closed
  actions: [open, close, describe]
  rules:
    open -> closed: 
      if action open:
        message: doorAlreadyOpen
        state: open
    closed -> open:
      if action close:
        message: doorAlreadyClosed
        state: closed
