door:
  default: closed
  actions: [open, close]
  rules:
    open -> closed: 
      - if action: close
      - then message: door_already_open
    closed -> open:
      - if action: open
      - then message: door_already_closed
